[project]
name = "graph-rag-recipes"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "datasets>=4.4.2",
    "ingredient-parser-nlp>=2.4.0",
    "nltk>=3.9.2",
    "spacy>=3.8.11",
    "tqdm>=4.67.1",
]
